sudo: required
language: node_js
node_js:
  - "node"
  - "6"

services:
  - docker

before_install:
  - docker --version
  - docker pull mariadb:latest
  - docker run -d --name db -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=testdb mariadb:latest
  - npm install

script:
  - npm test